#!/bin/bash
set -e
set -o pipefail


login() {
  if command -v pinentry-x11; then
    echo $(pinentry-x11 << EOS | grep -oP 'D \K.*' | op signin my > ~/.op/session
SETDESC Enter your 1password master password
GETPIN
EOS
    )
  fi
}

print-account-list() {
  op list items | jq -r '.[] | " - \(.overview.title) (\(.overview.ainfo)) [\(.uuid)]"'
  if [ ! $? -eq 0 ]; then
    login
    exit 0
  fi
}

open-account-url() {
  local url=$(op get item "$1" | jq -r '.overview.url')
  if [[ -n $url ]]; then
    xdg-open "$url" >/dev/null 2>/dev/null
  else
    exit 2
  fi
}

is-actual-url() {
  local url="$1"
  if [[ -n $url && "$url" != " " && "$url" != "http://" && "$url" != "https://" ]]; then
    return 0
  else
    return 1
  fi
}

show-account-options() {
  local id="$1"

  echo ">> Copy password [$id]"
  echo ">> Copy username [$id]"

  url=$(op get item "$id" | jq -r '.overview.url')
  if is-actual-url "$url"; then
    echo ">> Open $url [$id]"
    echo ">> Copy URL [$id]"
  fi

  echo ">> Copy ID [$id]"
}

is-entry-selected() {
  if [[ -n $@ ]]; then
    return 0
  else
    return 1
  fi
}

id-in-selection() {
  echo "$1" | grep -oE '\[[a-z0-9]+\]$' | tr -d '[]'
}

debug() {
  echo "$@" > /dev/stderr
}

if [[ -f ~/.op/session ]]; then
  source ~/.op/session
else
  login
fi

if is-entry-selected "$1"; then
  selected="$1"

  id="$(id-in-selection "$selected")"

  if [[ -n $id ]]; then
    case "$selected" in
      '>> Copy password'*)
        op get item "$id" | jq -j '.details.fields[] | select(.designation == "password") | .value' | xclip -selection c >/dev/null 2>/dev/null ;;
      '>> Copy username'*)
        op get item "$id" | jq -j '.details.fields[] | select(.designation == "username") | .value' | xclip -selection c >/dev/null 2>/dev/null ;;
      '>> Copy URL'*)
        op get item "$id" | jq -j '.overview.url' | xclip -selection c >/dev/null 2>/dev/null ;;
      '>> Copy ID'*)
        op get item "$id" | jq -j '.uuid' | xclip -selection c > /dev/null 2>/dev/null ;;
      '>> Open'*)
        open-account-url "$id" ;;
      *)
        show-account-options "$id" ;;
    esac
  else
    echo "Could not detect the entry ID of \"${selection}\""
    exit 1
  fi
else
  print-account-list
fi
