#!/bin/bash
set -e
set -o pipefail


: "${PINENTRY_PROGRAM:=pinentry-x11}"

login() {
  if command -v $PINENTRY_PROGRAM > /dev/null; then
    $PINENTRY_PROGRAM << EOS | grep -oP 'D \K.*' | op signin my > ~/.op/session
SETDESC Enter your 1password master password:
SETPROMPT Master Password:
GETPIN
EOS
  fi
  source ~/.op/session
}

print-account-list() {
  set +e
  op item list --format json | jq -r '.[] | "\(.title) (\(.additional_information)) [\(.id)]"'
  LOGGED_IN=${PIPESTATUS[0]}
  set -e

  if [ $LOGGED_IN -eq 127 ]; then
    echo "1password CLI tool 'op' not found"
    exit 2
  fi

  if [ ! $LOGGED_IN -eq 0 ]; then
    login
    print-account-list
  fi
}

open-account-url() {
  local url=$(op item get --format json "$1" | jq -r '.urls[] | select(.primary == true) | .href')
  if [[ -n $url ]]; then
    xdg-open "$url" >/dev/null 2>/dev/null
  else
    exit 2
  fi
}

is-actual-url() {
  local url="$1"
  if [[ -n $url && "$url" != " " && "$url" != "http://" && "$url" != "https://" ]]; then
    return 0
  else
    return 1
  fi
}

show-account-options() {
  local id="$1"
  local entry=$(op item get --format json "$id")

  echo ">> Copy password [$id]"
  echo ">> Copy username [$id]"

  if [[ -n $(echo $entry | jq -r '.fields[] | select(.value != null) | select(.type == "OTP")') ]]; then
    echo ">> Copy OTP [$id]"
  fi

  url=$(echo $entry | jq -r '.urls[] | select(.primary == true) | .href')
  if is-actual-url "$url"; then
    echo ">> Open $url [$id]"
    echo ">> Copy URL [$id]"
  fi

  echo ">> Copy ID [$id]"
}

is-entry-selected() {
  if [[ -n $@ ]]; then
    return 0
  else
    return 1
  fi
}

id-in-selection() {
  echo "$1" | grep -oE '\[[a-z0-9]+\]$' | tr -d '[]'
}

debug() {
  echo "$@" > /dev/stderr
}

if [[ ! -f ~/.op/session ]]; then
  login
fi
source ~/.op/session

if is-entry-selected "$1"; then
  selected="$1"

  id="$(id-in-selection "$selected")"

  if [[ -n $id ]]; then
    case "$selected" in
      '>> Copy password'*)
        op item get --format json "$id" | jq -r '.fields[] | select(.value != null) | select(.purpose == "PASSWORD") | .value' | xclip -selection c >/dev/null 2>/dev/null ;;
      '>> Copy username'*)
        op item get --format json "$id" | jq -r '.fields[] | select(.value != null) | select(.purpose == "USERNAME") | .value' | xclip -selection c >/dev/null 2>/dev/null ;;
      '>> Copy OTP'*)
        op item get --format json "$id" | jq -r '.fields[] | select(.value != null) | select(.type == "OTP") | .value' | xclip -selection c >/dev/null 2>/dev/null ;;
      '>> Copy URL'*)
        op item get --format json "$id" | jq -r '.urls[] | select(.primary == true) | .href' | xclip -selection c >/dev/null 2>/dev/null ;;
      '>> Copy ID'*)
        op item get --format json "$id" | jq -j '.id' | xclip -selection c > /dev/null 2>/dev/null ;;
      '>> Open'*)
        open-account-url "$id" ;;
      *)
        show-account-options "$id" ;;
    esac
  else
    echo "Could not detect the entry ID of \"${selection}\""
    exit 1
  fi
else
  print-account-list
fi
